### ISSUE TITLE
System.Net.Sockets.SocketException

### ISSUE THREAD

**Issue by troyBORG** [RubberDuckShobe/NeosSpotifyStatus#3]
```
PS C:\Users\troyB\Downloads\NeosSpotifyStatus> .\NeosSpotifyStatus.exe
 04:16:29.037 INF >> [WebServer] Running HTTPListener: Unosquare HTTP Listener
 04:16:29.049 INF >> [WebServer] Web server prefix 'http://*:5000/' added.
 04:16:29.098 INF >> [WebServer] Started HTTP Listener
WebSocket Server running at: 127.0.0.1:1011
Unhandled exception. System.Net.Sockets.SocketException (10048): Only one usage of each socket address (protocol/network address/port) is normally permitted.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpListener.Start(Int32 backlog)
   at System.Net.Sockets.TcpListener.Start()
   at WebSocketSharp.Server.WebSocketServer.startReceiving()
   at WebSocketSharp.Server.WebSocketServer.Start()
   at Program.Main()
   at Program.<Main>()
PS C:\Users\troyB\Downloads\NeosSpotifyStatus>
```

**Comment by RubberDuckShobe** [comment]
Are you sure that port 1011 is free? Try running netstat -a in
cmd/powershell and take a look at the "Local Address" column, maybe there's
another program using that port already.
